package cli

import (
	"context"
	"fmt"
	"io"
	"net"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"github.com/jingkaihe/comet/internal/server"
	"github.com/spf13/cobra"
)

const defaultServePort = 6174

type ServeConfig struct {
	Host            string
	Port            int
	AuthToken       string
	Theme           string
	SkipAuth        bool
	Background      bool
	backgroundChild bool
	InstanceID      string
}

func NewServeConfig() *ServeConfig {
	return &ServeConfig{
		Host: "localhost",
		Port: defaultServePort,
	}
}

func newServeCommand() *cobra.Command {
	defaults := NewServeConfig()
	config := NewServeConfig()

	cmd := &cobra.Command{
		Use:   "serve",
		Short: "Start the Comet web terminal server",
		Long: fmt.Sprintf(`Start a local web server that provides a browser terminal.

The server is available at http://localhost:%d by default. A random token is
generated unless --auth-token is provided or --skip-auth is set.`, defaultServePort),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runServeCommand(cmd.Context(), config, cmd.OutOrStdout())
		},
	}

	cmd.Flags().StringVar(&config.Host, "host", defaults.Host, "Host to bind the web server to")
	cmd.Flags().IntVar(&config.Port, "port", defaults.Port, "Port to bind the web server to")
	cmd.Flags().StringVar(&config.AuthToken, "auth-token", defaults.AuthToken, "Token required to access the web UI; generated by default")
	cmd.Flags().StringVar(&config.Theme, "theme", defaults.Theme, "Terminal theme to use by default")
	cmd.Flags().BoolVar(&config.SkipAuth, "skip-auth", defaults.SkipAuth, "Disable web UI token authentication")
	cmd.Flags().BoolVar(&config.Background, "background", defaults.Background, "Start the web terminal server in the background")
	cmd.Flags().BoolVar(&config.backgroundChild, "background-child", defaults.backgroundChild, "Run as an internal background child process")
	cmd.Flags().StringVar(&config.InstanceID, "instance-id", defaults.InstanceID, "Internal background server instance ID")
	_ = cmd.Flags().MarkHidden("background-child")
	_ = cmd.Flags().MarkHidden("instance-id")

	return cmd
}

func validateServeConfig(config *ServeConfig) error {
	if config.Host == "" {
		return fmt.Errorf("host cannot be empty")
	}

	if config.Host != "localhost" && config.Host != "0.0.0.0" {
		if ip := net.ParseIP(config.Host); ip == nil {
			if strings.Contains(config.Host, " ") || strings.Contains(config.Host, ":") {
				return fmt.Errorf("invalid host: %s", config.Host)
			}
		}
	}

	if config.Port < 1 || config.Port > 65535 {
		return fmt.Errorf("port must be between 1 and 65535, got %d", config.Port)
	}

	if config.SkipAuth && config.AuthToken != "" {
		return fmt.Errorf("--auth-token cannot be used with --skip-auth")
	}

	if err := server.ValidateAuthToken(config.AuthToken); err != nil {
		return err
	}

	return server.ValidateThemeName(config.Theme)
}

func runServeCommand(ctx context.Context, config *ServeConfig, out io.Writer) error {
	if err := validateServeConfig(config); err != nil {
		return fmt.Errorf("invalid server configuration: %w", err)
	}
	if config.Background {
		if config.backgroundChild {
			return fmt.Errorf("--background cannot be used with internal background child mode")
		}

		return runServeBackground(ctx, config, out)
	}

	return runServeForeground(ctx, config, out)
}

func runServeForeground(ctx context.Context, config *ServeConfig, out io.Writer) error {
	authToken := strings.TrimSpace(config.AuthToken)
	if !config.SkipAuth && authToken == "" {
		var err error
		authToken, err = server.NewToken()
		if err != nil {
			return fmt.Errorf("failed to generate auth token: %w", err)
		}
	}

	terminalServer, err := server.New(&server.Config{
		Host:       config.Host,
		Port:       config.Port,
		AuthToken:  authToken,
		Theme:      config.Theme,
		InstanceID: config.InstanceID,
	})
	if err != nil {
		return fmt.Errorf("failed to create web server: %w", err)
	}
	defer terminalServer.Close()

	ctx, cancel := signal.NotifyContext(ctx, os.Interrupt, syscall.SIGTERM)
	defer cancel()

	baseURL := serveBaseURL(config.Host, config.Port)
	fmt.Fprintf(out, "Comet web terminal starting on %s\n", baseURL)
	if authToken != "" {
		fmt.Fprintf(out, "Authentication token: %s\n", authToken)
		fmt.Fprintf(out, "Open this URL: %s\n", serveURLWithToken(baseURL, authToken))
	} else {
		fmt.Fprintln(out, "Authentication disabled (--skip-auth)")
	}
	fmt.Fprintln(out, "Press Ctrl+C to stop the server")

	if err := terminalServer.Start(ctx); err != nil {
		return fmt.Errorf("web server failed: %w", err)
	}

	fmt.Fprintln(out, "Comet web terminal stopped")
	return nil
}

func serveBaseURL(host string, port int) string {
	displayHost := host
	if displayHost == "" || displayHost == "0.0.0.0" || displayHost == "::" {
		displayHost = "localhost"
	}
	if strings.Contains(displayHost, ":") && !strings.HasPrefix(displayHost, "[") {
		displayHost = "[" + displayHost + "]"
	}

	return fmt.Sprintf("http://%s:%d", displayHost, port)
}

func serveURLWithToken(baseURL string, authToken string) string {
	parsedURL, err := url.Parse(baseURL)
	if err != nil {
		return baseURL
	}

	query := parsedURL.Query()
	query.Set("token", authToken)
	parsedURL.RawQuery = query.Encode()
	return parsedURL.String()
}
